### ISSUE TITLE
Add vfp optimizations from bjude

### ISSUE THREAD

**Issue by gizmo98** [ricrpi/mupen64plus-video-gles2n64#14]
I would like to see bjudes work merged for rpi1:
https://github.com/bjude/mupen64plus-video-gles2n64/commit/36acc229f06c5ed5b4da9270e8fb8dbbb6f2aa96

@bjude is your work ready to go?

**Comment by bjude** [comment]
I wrote this vfp code ages ago and haven't been able to work on it until very recently due to work ,and a busted SD means i actually haven't compiled this stuff yet. I had it compiled and working a while ago but not with the current master.

looking over the commit, it should all compile and work fine but i'd need someone to test it for me, i just wont have the time for a few weeks.

The only issue might me ensuring that the VFP optimisations are only compiled with the rpi 1 and not the rpi 2 (which has a neon coprocessor).

**Comment by gizmo98** [comment]
Ok. I added your code and tested it a little bit. I haven't seen any issue so i merged it. VFP is optional. If there is a issue don't set VFP=1.
